Attempt to validate fields that are calculated.
formio/formio.js pull request #2968
Opened 2020-06-18 20:33 UTC by nathanieltagg

Attempt to fix bug 2948, but it is rather ham-fisted.

If a Component has a this.calculatedValue, then always check for validity.
Exception: don't do it if the calculatedValue is NaN, which happens frequently if the form is empty. 

But that isn't really perfect, because you might want to validate a case where
value = data.a/data.b
which would generate an NaN that you want to validate against.

2020-06-20 19:09 UTC, travist commented
This change kind of scares me. I will add this to our Monday discussion to talk through what the right approach to solving this issue will be.

2020-06-22 13:47 UTC, nathanieltagg commented
Fair enough - as I said, it's a hack where I don't really understand the cause of the problem. It's a workaround for me in the meantime.

2020-06-22 15:22 UTC, wag110894 commented
@nathanieltagg, do you not agree with @airarrazaval on his comment that this is working as expected: https://github.com/formio/formio.js/issues/2948

2020-06-23 14:30 UTC, nathanieltagg commented
@wag110894  I would say that it may be working as intended, but not as (I) expected.  If calculated values cannot be validated, this should be disabled in the builder menu and documented.

But I would prefer just to make it work, because I see no reason, in principle, why it shouldn't work.

2020-09-07 15:01 UTC, travist requested changes

2020-09-07 15:01 UTC, travist commented on src/components/_classes/component/Component.js
> +    if (this.calculatedValue !== undefined && !(Number.isNaN(this.calculatedValue) && !calcChanged)) {
I am ok with this change as long as we do not make an assumption that calculated values should be numbers. You can create a calculated value as any data type. The name should really be computedValue

2020-09-27 17:49 UTC, travist requested changes
Requesting changes before we can pull this in. Please remove assumption calculated values must be numbers.

2020-12-16 16:22 UTC, travist commented
Closing due to lack of activity. We have also recently refactored calculated values (and we have not heard of any other customers complain about this), so I assume it is no longer a pressing issue.

2020-12-16 16:22 UTC, closed without merging