FJS-1380: Adds a validation which checks if the value is available within component's values setting
formio/formio.js pull request #3504
Opened 2020-11-19 11:59 UTC by alexandraRamanenka

2020-11-19 15:21 UTC, AlexeyDavyd approved these changes

2020-11-19 19:03 UTC, MaksimFalei approved these changes

2020-11-20 15:59 UTC, travist requested changes

2020-11-20 15:59 UTC, travist commented on src/i18n.js
> +        valueIsNotAvailable: '{{field}} conatains unavailable value',
Can we change this to say ```{{ field }} is an invalid value.```

2020-11-20 16:49 UTC, MaksimFalei approved these changes

2020-11-20 17:17 UTC, merged