Translation issue Fixed
formio/formio.js pull request #3613
Opened 2020-12-29 09:24 UTC by syed-farjana

There is translation  issue in edit grid validation. Added the translation code like the other component

2021-01-02 16:35 UTC, travist commented
There is now a conflict. Please resolve and we will pull in this change.

2021-01-04 06:49 UTC, syed-farjana commented
Resolved the conflict please Review

2021-01-05 14:51 UTC, travist requested changes

2021-01-05 14:51 UTC, travist commented on src/components/editgrid/EditGrid.js
> -            errorContainer.textContent = this.t('invalidRowError');
So, this should be picked up with the following.

https://github.com/formio/formio.js/blob/master/src/i18n.js#L11

Why is this not registering correctly?  I feel like this is not fixing the actual bug here...

2021-01-06 06:34 UTC, syed-farjana commented
I think the above changes are in master branch.  but in 4.12.x the above  translation changes are not there.

2021-01-08 14:48 UTC, travist commented
Then we should Port the "master" changes into the 4.12.x branch, and that should be included in this pull request.

2021-01-11 05:26 UTC, syed-farjana commented
you mean it de we need to merge master and 4.12.x. I guess I can't do this. Can you suggest what I can do here

2021-01-11 15:26 UTC, travist commented
You can branch off of the 4.12.x branch, and then when you submit your pull request, you can change the "base" branch to merge into. It is part of the Github pull request process.

2021-05-30 20:39 UTC, closed without merging