fix resource forms didn't transfer settings to pdf
formio/formio.js pull request #3762
Opened 2021-02-11 14:23 UTC by mikekotikov

2021-02-12 08:55 UTC, MaksimFalei approved these changes

2021-02-13 23:42 UTC, travist requested changes

2021-02-13 23:42 UTC, travist commented on src/PDFBuilder.js
> +      const info = this.getComponentInfo(key, group);
This fix kind of seems like a hack to me. Can we discuss this fix in developer support meeting?

2021-02-18 14:44 UTC, travist commented
We discussed, and it is fine. This will be included in next build.

2021-02-18 15:39 UTC, MaksimFalei approved these changes

2021-02-21 20:02 UTC, merged