FJS - 1294 Text Area - When Text area is empty but has a default row greater than 1 , text row shows as one line when submission is viewed
formio/formio.js pull request #3924
Opened 2021-04-05 09:44 UTC by yavorovsky

2021-05-12 14:29 UTC, yavorovsky commented
changed view styles for the textarea's submission view. I don't think it has to be tested by automation tests

2021-05-21 14:51 UTC, travist requested changes

2021-05-21 14:51 UTC, travist commented on src/components/textarea/TextArea.js
> +    const brake = '<br>';
It should be "break" not "brake".

Also, this seems very heavy handed to solve this minor issue. There is not an easier way to solve this?

2021-05-30 20:45 UTC, travist commented
We need a more simple way to solve this problem.

2021-05-30 20:45 UTC, closed without merging