FJS | Calculated Data in DataSource in Edit Mode is not working
formio/formio.js pull request #3965
Opened 2021-04-13 09:33 UTC by yavorovsky

2021-05-11 00:34 UTC, irshadmb approved these changes

2021-05-12 04:16 UTC, travist commented
Please write some tests.

2021-05-13 08:40 UTC, yavorovsky commented
@travist, done

2021-05-14 08:11 UTC, yavorovsky commented
@travist , I updated the renders and merged master to pass tests.

2021-05-21 14:40 UTC, travist requested changes

2021-05-21 14:40 UTC, travist commented on src/components/_classes/component/Component.js
> +    if (!flags.fromSubmission && !this.root.editing || !this.component.persistent) {
These checks should just be added to the checks on line 2596.

2021-05-25 14:12 UTC, travist commented on src/components/_classes/component/Component.js
> +    if (!flags.fromSubmission && !this.root.editing || !this.component.persistent) {
Disregard this comment.

2021-05-25 14:12 UTC, merged