FIO-2848, FIO-2831: Fix/edit grid errors alerts
formio/formio.js pull request #4041
Opened 2021-04-28 13:47 UTC by alexandraRamanenka

2021-04-30 10:02 UTC, elibus commented
It would be great if this could make it in the next 4.13.1 @heather-formio

2021-05-01 19:51 UTC, alexandraRamanenka commented
> Please write some tests.

Sure, I am just waiting for the response of the customer to confirm some aspects of the component's behavior to finish this PR.

2021-05-03 18:46 UTC, travist requested changes
Also needs tests.

2021-05-03 18:46 UTC, travist commented on src/components/panel/Panel.js
> +  //
I would rather just delete this code instead of comment it out. We can use GIT to see what was removed.

2021-05-12 08:14 UTC, kamsi commented
@alexandraRamanenka thing is that I totally need to reflect that selection on a data level. My use case involves saving that choice for later for example. I guess that with your change we move the logic to the purely component render level and so the choice is not persisted, right (or maybe I do not get how editRow works exactly)? So, the way I see it it breaks my use case.

2021-05-12 10:04 UTC, alexandraRamanenka commented
So then, you need something like a hidden checkbox with 'isRowSelected' key and add events for handling when the row is selected/deselected. Using Advanced logic you can set the checkbox to change it value once it receives one of those events. 
Because "silently" changing the dataValue and adding/removing new keys to it is not we want to do, it could lead to very unexpected and undesired behavior (I have already found few cases when it totally breaks EditGrid)

2021-05-12 10:10 UTC, kamsi commented
@alexandraRamanenka OK, thanks for the guidance, I will look into event based handling with advanced logic + hidden checkbox. And thank you for notifying me explicitly in the first place about the change.

2021-05-12 10:13 UTC, alexandraRamanenka commented
> @alexandraRamanenka OK, thanks for the guidance, I will look into event based handling with advanced logic + hidden checkbox. And thank you for notifying me explicitly in the first place about the change.

No problem. If you have any questions or need an example, you can ask me.

2021-05-14 13:14 UTC, elibus commented
Thanks @alexandraRamanenka 
@travist can we have a rc with this please?

2021-05-18 14:35 UTC, merged

2021-05-19 21:19 UTC, heather-formio commented
@elibus This pull request has been merged and is part of Formio.js version 4.14.0-RC.6. Let us know if you have any questions.

2021-05-20 06:41 UTC, elibus commented
Thanks @heather-formio we saw also rc.6 includes the other patch in 4.13, it seems to work fine. Thanks to @travist and @alexandraRamanenka as well 👍