UIP-317: Fixes protected eval crushing
formio/formio.js pull request #4594
Opened 2022-02-15 12:07 UTC by mikekotikov

2022-04-06 15:35 UTC, travist requested changes

2022-04-06 15:35 UTC, travist commented on src/components/_classes/component/Component.js
> +      options: FormioUtils.Evaluator.protectedEval ? {} : this.options,
This change does not make much sense. You do not wish to pass the options if we are using protectedEval plugin?  I do not understand how this would affect the renderer.

2022-04-06 18:33 UTC, mikekotikov commented on src/components/_classes/component/Component.js
> +      options: FormioUtils.Evaluator.protectedEval ? {} : this.options,
I can actually move this to `protected-eval` exclusions, as [here](https://github.com/formio/protected-eval/blob/master/src/ProtectedEvaluator.ts#L14)
Because many properties in `options` cause stack overflow as they get infinitely converted to js-interpreter objects

2022-04-07 03:10 UTC, travist commented on src/components/_classes/component/Component.js
> +      options: FormioUtils.Evaluator.protectedEval ? {} : this.options,
Yep that will work. I like that better. Just move it into the protected-eval plugin.

2022-04-07 06:00 UTC, closed without merging