Added basic keyboard accessibility for formbuilder
formio/formio.js pull request #4680
Opened 2022-04-21 13:41 UTC by antonSoftensity

2023-01-13 10:26 UTC, TanyaGashtold approved these changes

2023-01-13 10:30 UTC, TanyaGashtold requested changes
Please confirm that tests are passing at least locally

2023-01-27 15:08 UTC, antonSoftensity commented
tests are passing locally after rebasing master branch

2023-01-27 15:12 UTC, TanyaGashtold approved these changes

2023-03-15 06:40 UTC, TanyaGashtold approved these changes

2023-03-15 06:56 UTC, merged