FIO-4318: fixed displaying data for select with url data src
formio/formio.js pull request #4876
Opened 2022-09-27 10:32 UTC by Maria-Golomb

2023-01-16 11:17 UTC, TanyaGashtold requested changes

2023-01-16 11:17 UTC, TanyaGashtold commented on src/components/select/Select.js
> +        }
I am pretty sure that this solution causes regressions.

1) Always setting search input equal to dataValue means that select dropdown will always show only 1 option, that is equal to dataValue.
2) According to the changes, select Url will never update items on 'hideDropdown', that means that only found by search items will be shown when you open the dropdown again.

Please spend more time to investigate the issue.

2023-01-16 11:17 UTC, TanyaGashtold commented on src/components/select/Select.js
> +        }
Please fix tests.

2023-07-21 13:44 UTC, lane-formio commented
Issue no longer reproduceable, closing PR.

2023-07-21 13:44 UTC, closed without merging