FIO-7847: Highlight components that have API keys consisting only fro…
formio/formio.js pull request #5522
Opened 2024-02-22 15:11 UTC by alexandraRamanenka

## Link to Jira Ticket

https://formio.atlassian.net/browse/FIO-7847

## Description

Use regular expressing that the server does before saving the form to highlight invalid form components

## Dependencies

*This PR depends on the following PRs from other Form.io modules: ...*

## How has this PR been tested?

*I added automated tests to cover [all/the following] cases, including ...*

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] My changes generate no new warnings
- [ ] My changes include tests that prove my fix is effective (or that my feature works as intended)
- [ ] New and existing unit/integration tests pass locally with my changes
- [ ] Any dependent changes have corresponding PRs that are listed above

2024-04-17 13:16 UTC, AlexeyNikipelau requested changes

2024-04-17 13:16 UTC, AlexeyNikipelau commented on src/WebformBuilder.js
> +    const badCharacters = /^[^A-Za-z_]+|[^A-Za-z0-9\-._]+/g;
Please, comment what this regex is doing

2025-02-12 16:33 UTC, brendanbond requested changes
the new tests are failing

2025-05-29 16:15 UTC, johnformio approved these changes

2025-06-11 20:35 UTC, brendanbond approved these changes

2025-06-11 20:35 UTC, merged