FIO-8281: fixed selectData property for multiple select component
formio/formio.js pull request #5592
Opened 2024-05-10 13:10 UTC by roma-formio

## Link to Jira Ticket

https://formio.atlassian.net/browse/FIO-8281

## Description

Fixed the issue regarding setting selectData property for the multiple select component.

## Dependencies

https://github.com/formio/core/pull/93

## How has this PR been tested?

Unit testing

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if applicable)
- [x] My changes generate no new warnings
- [x] My changes include tests that prove my fix is effective (or that my feature works as intended)
- [x] New and existing unit/integration tests pass locally with my changes
- [x] Any dependent changes have corresponding PRs that are listed above

2024-05-13 19:52 UTC, brendanbond approved these changes

2024-05-13 19:53 UTC, brendanbond requested changes
It looks like your new tests are failing

2024-05-14 13:32 UTC, roma-formio commented
> It looks like your new tests are failing

Yes, they're failing because my changes depend on @formio/core validation changes for the URL Select Component. In the current version it's impossible to create the multiple URL select component with default value and my test is trying to do this.

2024-05-21 12:18 UTC, brendanbond commented
> > It looks like your new tests are failing
> 
> Yes, they're failing because my changes depend on @formio/core validation changes for the URL Select Component. In the current version it's impossible to create the multiple URL select component with default value and my test is trying to do this.

Gotcha. FYI we've just introduced a CICD system that's pretty cool - your [@formio/core PR](https://github.com/formio/core/pull/93) automatically built and published a dev-tagged version of the core lib to NPM (2.0.0-dev.93.5a2c62c) so we can now update these dependencies in our PRs to make sure tests are passing! I've gone ahead and pushed an update to this PR to update the version of @formio/core.

2024-06-04 17:28 UTC, merged