FIO-8366: API key is not unique translation
formio/formio.js pull request #5613
Opened 2024-05-23 16:07 UTC by ZenMasterJacob20011

## Link to Jira Ticket

https://formio.atlassian.net/browse/FIO-8366

## Description

**What changed?**

- API key validation errors now are able to be translated using the apiKey property. This is possible now because the apiKey property was added to en.js translation file and the highlightInvalidComponents function which is responsible for setting the apiKey validation error now uses this.t("apiKey") instead of hard coding the error. The apiKey is also passed in the context of what apiKey is causing the error using comp.key. 
- The check to remove "api key is not unique" error message from the form is unnecessary as the check for invalid api keys is made when the form build is saved and the form builder will redraw the components upon saving which removes the apiKey error

## Dependencies

## How has this PR been tested?

manually

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if applicable)
- [x] My changes generate no new warnings
- [ ] My changes include tests that prove my fix is effective (or that my feature works as intended)
- [ ] New and existing unit/integration tests pass locally with my changes
- [ ] Any dependent changes have corresponding PRs that are listed above

2024-05-23 20:27 UTC, brendanbond requested changes
Tests are failing.

2024-05-24 13:30 UTC, travist commented
You need to write a test for this.

2024-05-24 18:25 UTC, ZenMasterJacob20011 commented
Added Tests. Also added some render html files generated from running test:updateRenders because if you add a json file to formtest directory the render tests expect a rendered html file of that json in the renders directory

2024-05-30 04:29 UTC, brendanbond approved these changes

2024-05-30 04:29 UTC, merged