Replace in utils fastCloneDeep func cloning with json.parse-stringiry to structuredClone api
formio/formio.js pull request #5942
Opened 2024-12-06 21:13 UTC by kievsash

## Link to Jira Ticket

https://formio.atlassian.net/browse/FIO-XXXX
https://github.com/formio/angular/issues/1016

## Description

**What changed?**
in utils fastCloneDeep now native API structuredClone is used instead of JSON.parse(JSON.stringify(obj))

*Use this section to provide a summary description of the changes you've made*

**Why have you chosen this solution?**
Native browser API
And structuredClone allows to keep File object in event copy. More details in question link above https://github.com/formio/angular/issues/1016

*Use this section to justify your choices*
allows to keep File object in event copy. More details in question link above https://github.com/formio/angular/issues/1016
## Breaking Changes / Backwards Compatibility

*Use this section to describe any potentially breaking changes this PR introduces or any effects this PR might have on backwards compatibility*
no breaking changes
## Dependencies

*Use this section to list any dependent changes/PRs in other Form.io modules*

## How has this PR been tested?

*Use this section to describe how you tested your changes; if you haven't included automated tests, justify your reasoning*

## Checklist:

- [ ] I have completed the above PR template
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] My changes generate no new warnings
- [ ] My changes include tests that prove my fix is effective (or that my feature works as intended)
- [ ] New and existing unit/integration tests pass locally with my changes
- [ ] Any dependent changes have corresponding PRs that are listed above

2024-12-06 21:14 UTC, kievsash commented
cc @travist

2025-02-11 16:20 UTC, brendanbond requested changes
Thanks for the PR! Normally I'd be all for this, but there are a couple of things I think are not considered here:

1. Not so important, but we'd probably want a polyfill here or at least a test for browser compatibility.
2. Much more importantly, we use this fastCloneDeep utility on the server, included in isolated environments with no access to browser APIs. We're going to need to confirm whether this change would affect the ability of a clone operation to, for example, clone mongodb ObjectIds

2025-02-27 13:45 UTC, lane-formio commented
<div>Agent Viktoryia Alennikava linked Freshdesk ticket <a href="https://formhelp.freshdesk.com/a/tickets/55607">55607</a> for this issue.</div><br/>

2025-03-11 20:47 UTC, johnformio commented
structuredClone does not parse mongodb objects precisely,  You can run this in a node repl.
```
> const ObjectID = require('mongodb').ObjectId;
undefined
> let id = new ObjectID()
undefined
> let obj = {id}
undefined
> let obj2 = structuredClone(obj)
undefined
> obj2
{
  id: {
    buffer: Uint8Array(12) [
      103, 208, 160, 181,
       50, 204, 159, 154,
      190, 225,  37,  15
    ]
  }
}
> obj
{ id: new ObjectId('67d0a0b532cc9f9abee1250f') }
> 
```

2025-03-11 21:35 UTC, brendanbond commented
Hey @kievsash - wanted to truly thank you for opening this PR, but unfortunately the risks outweigh the benefits here when we're doing server side processing of complex objects and using the fast JSON parse isn't really causing any issues that I can observe. Have you seen any issues that would necessitate us moving to structuredClone?

2025-03-12 19:00 UTC, kievsash commented
Hi @brendanbond 
The case is described here: https://github.com/formio/angular/issues/1016

2025-04-09 15:55 UTC, merged

2025-04-09 18:25 UTC, brendanbond commented
hey @kievsash I have to revert this change - normally our CI/CD runs tests, and I didn't notice that they didn't run on this PR and they are now failing due to this change

2025-04-09 19:21 UTC, kievsash commented
Just noticed I dont have permision to reopen

2025-04-09 19:23 UTC, johnformio commented
done